### ISSUE TITLE
Multi-line text entry improvements — Load text from file(s)

### ISSUE THREAD

**Issue by Shrinks99** [coldtype/coldtype-blender#4]
It would seem that Blender somehow does not have a multi-line text editor for data entry.  What a bummer!  I can only assume that this is the reason that Coldtype in Blender only accepts a single string with paragraph break control characters to add a new line... A less than awesome user experience if I'm being honest :P

Until the lovely folks at the Blender Foundation get around to adding this feature, I'd propose the ability to load text from a file?  As a bonus maybe also the ability to load multiple text files as a frame sequence?  The option to externalize the actual editing of text has some neat pipeline opportunities as well? 🤔

**Comment by stenson** [comment]
Yeah was thinking about adding text-from-file support, that would be a fun feature. Will update this thread when I've made some progress there.

**Comment by stenson** [comment]
New option to use both external files and internal text blocks (for an all in-blender text-editing-with-newlines experience) — just released with the 0.5 release (https://github.com/coldtype/coldtype-blender/releases/tag/v0.5) — posted a video about it here: https://twitter.com/robstenson/status/1569428730409517057
